
on:
  push:
    branches:    
      - main

name: IbGateway
jobs:
  build-and-test:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}            
  
      - name: Build image
        run: |
          docker build -t ghcr.io/utopleman/phoenix/ibgateway:${{github.sha}} .
        shell: bash

      - name: Push image
        run: |
          docker tag ghcr.io/utopleman/phoenix/ibgateway:${{github.sha}} ghcr.io/utopleman/phoenix/ibgateway:latest
          docker push ghcr.io/utopleman/phoenix/ibgateway:latest
        shell: bash
